version: '3'

volumes:
    db:
    node_modules:
    prod_code:
  
services:
    vue-cli:
        build: frontend/. 
        ports:
            - "8000:8000"
        volumes:
            - ./frontend/code:/code
            - prod_code:/code/prod
            - node_modules:/code/node_modules

    backend:
        build: backend/.
        volumes:
            - ./backend/code:/code
        environment:
            - MONGO_USERNAME=devbase
            - MONGO_PASSWORD=devbase
            - MONGO_DATABASE=devbase
            - MONGO_HOSTNAME=mongo
    
    redis:
        image: "redis:alpine"

    nginx:
        image: "nginx"
        ports:
            - "5000:5000"
        volumes:
            - ./nginx.dev.conf:/etc/nginx/conf.d/nginx.dev.conf
            - prod_code:/html
                 
    mongo:
        build: db/.
        environment:
            - MONGO_INITDB_ROOT_USERNAME=dbadmin
            - MONGO_INITDB_ROOT_PASSWORD=somepassword
            - MONGO_INITDB_DATABASE=devbase
        volumes:
            - db:/data/db

    mongo-express:
        image: "mongo-express"
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_ADMINUSERNAME=dbadmin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=somepassword
            - ME_CONFIG_MONGODB_AUTH_DATABASE=devbase
            - ME_CONFIG_SITE_BASEURL=/db/

    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
        - REDIS_HOSTS=local:redis:6379
        ports:
        - "8081:8081"
            
    